export const SocketEvent = {
  RoomCreate: "room:create",
  RoomJoin: "room:join",
  RoomLeave: "room:leave",
  RoomSetCapacity: "room:setCapacity",
  RoomStart: "room:start",
  RoomState: "room:state",
  RoomError: "room:error",
  ProfileUpdate: "profile:update",
  ProfileMoveItem: "profile:moveItem",
  MatchStarted: "match:started",
  MatchTimer: "match:timer",
  MatchSettlement: "match:settlement",
  StatePlayers: "state:players",
  StateMonsters: "state:monsters",
  StateDrops: "state:drops",
  PlayerInputMove: "player:inputMove",
  PlayerAttack: "player:attack",
  PlayerCastSkill: "player:castSkill",
  PlayerPickup: "player:pickup",
  PlayerDropItem: "player:dropItem",
  PlayerEquipItem: "player:equipItem",
  PlayerUnequipItem: "player:unequipItem",
  PlayerMoveInventoryItem: "player:moveInventoryItem",
  PlayerUseItem: "player:useItem",
  PlayerStartExtract: "player:startExtract",
  PlayerDisconnected: "player:disconnected",
  CombatResult: "combat:result",
  InventoryUpdate: "inventory:update",
  LootSpawned: "loot:spawned",
  LootPicked: "loot:picked",
  PlayerDied: "player:died",
  ExtractOpened: "extract:opened",
  ExtractProgress: "extract:progress",
  ExtractSuccess: "extract:success",
  ChestsInit: "chests:init",
  ChestOpened: "chest:opened",
  PlayerOpenChest: "player:openChest"
} as const;

export type SocketEventName = (typeof SocketEvent)[keyof typeof SocketEvent];
